# Generated by Django 3.2.8 on 2021-10-27 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=60)),
                ('ip', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('severity', models.CharField(max_length=10)),
                ('cvss', models.FloatField(blank=True, default=None, null=True)),
                ('publication_date', models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'vulnerabilities',
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityInAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asset')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vulnerability')),
            ],
            options={
                'db_table': 'vulnerabilities_in_assets',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='vulnerabilities',
            field=models.ManyToManyField(through='api.VulnerabilityInAsset', to='api.Vulnerability'),
        ),
    ]
